### ISSUE TITLE
Error after installing Trebleshot 0.1.0-alpha on Windows

### ISSUE THREAD

**Issue by Keridos** [trebleshot/desktop#6]
![image](https://user-images.githubusercontent.com/2742845/56255958-19da3500-60c7-11e9-9ab2-93fdfd84d14e.png)

**Comment by Dinxton** [comment]
I'm getting the same error. Windows 10 1809 (Build 17763.437), [DXDiag](https://pastebin.com/aNGVL4Pi), installed from the binary installer. 
![image](https://user-images.githubusercontent.com/6743231/56574765-f843e680-65bb-11e9-9bd2-b77100eae295.png)

**Comment by velitasali** [comment]
I am guessing this happens because SQLite3 driver is missing. But it is only a guess though.

I will look into this.

**Comment by gschurck** [comment]
Yes I have the same issue

**Comment by velitasali** [comment]
https://github.com/genonbeta/TrebleShot-Desktop/releases/download/0.1.0-alpha2/TrebleShot-0.1.0-installer.exe

This fixes it.

**Comment by tallship** [comment]
Installed okay w/o any errors, but I can't get any transfers or recognition of either devices. When I put in the IP of the phone it does resolve the name, but fails to connect. 

When I try to connect from the phone, I connect to the WiFi hotspot on the win10/64 machine just  fine w/the wifi client on the phone, but then there's no way to use QR codes to link the devices.

Looking forward to this maturing and hopefully a manual for linking desktop and Android devices. It's late now so I'll continue troubleshooting connections and file transfers again over the next few days.

**Comment by tallship** [comment]
Installed okay w/o any errors, but I can't get any transfers or recognition of either devices. When I put in the IP of the phone it does resolve the name, but fails to connect. 

When I try to connect from the phone, I connect to the WiFi hotspot on the win10/64 machine just  fine w/the wifi client on the phone, but then there's no way to use QR codes to link the devices.

Looking forward to this maturing and hopefully a manual for linking desktop and Android devices. It's late now so I'll continue troubleshooting connections and file transfers again over the next few days.

**Comment by velitasali** [comment]
@tallship Please open another issue for your problem so that others can find and comment on it as well. Closing this issue for now.
